### PR TITLE
(SIMP-6638) Allow nsswitch overrides

### PR DESCRIPTION
**Pull request by silug**
SIMP-6638 #close

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@silug Could you check the Travis results and see if this is expected?

**Comment by silug** [comment]
@trevor-vaughan I don't understand how this test ever passed..  https://travis-ci.org/simp/pupmod-simp-simp/jobs/574977848#L2275 is showing a failure at https://github.com/silug/pupmod-simp-simp/blob/c78cc4e1dcb3ee7b3052a58c39c37edac37f8a6f/spec/classes/00_classes/nsswitch_spec.rb#L21 because the contents are different on centos-6-x86_64, which should have been true on the original code.

**Comment by trevor-vaughan** [comment]
@silug Will double check.

**Comment by trevor-vaughan** [comment]
Rebased and tests updated. I agree that I have no idea why they were working before.

**Pull request merged**
