### PR TITLE
(SIMP-4399) Update tests with minor/patch deps changes

### PR DESCRIPTION
**Pull request by lnemsick-simp**
SIMP-4399 #comment pupmod-simp-simp fixtures update

### CODE REVIEW

**Comment by jeefberkey** [comment]
🔴 https://gitlab.com/simp/pupmod-simp-simp/pipelines/17333028

**Comment by trevor-vaughan** [comment]
@jeefberkey I think this sparked the conversation about ditching `activemq` and `mcollective`. We probably need to do that instead of spending time trying to patch things that nobody supports any longer.

**Comment by jeefberkey** [comment]
@trevor-vaughan I'd like to see the acceptance tests run

**Comment by trevor-vaughan** [comment]
SIMP-4002 #close

**Comment by jeefberkey** [comment]
🕥 Waiting for https://gitlab.com/simp/pupmod-simp-simp/pipelines/17474776

**Pull request merged**
