### PR TITLE
Add cloud class to safeguard cloud installations

### PR DESCRIPTION
**Pull request by jeefberkey**

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@jeefberkey I see the reasonableness to this approach but have a few questions.

1. This doesn't really seem SIMP-specific, should it go in its own module?
2. This seems more like `virtualization` than `cloud`

**Comment by jeefberkey** [comment]
@trevor-vaughan virtualization is too specific of a definition for this imo. The `aws` facts have the virtualization key (or something like it) and it's always set to `hvm` or something. `cloud` is a bit more generic and git the majority use case.

I would be down for a `running_in_bolt` fact. Last time I asked how to detect when puppet code was run in bolt, the only reliable answer I got was the environment. It's not ideal.

**Comment by trevor-vaughan** [comment]
Created a `simplib::in_bolt()` function to handle this in a future-proof manner.

**Comment by trevor-vaughan** [comment]
@jeefberkey This is the reason that I said it was more than cloud: https://github.com/simp/pupmod-simp-simp/pull/188/files#diff-c88cf8fe16dd3d9d15691b4da4e2daa4R3.

I see the point of this but I'm not sure it should be a default since it's relatively difficult to test in an automated fashion (excepting `vagrant`).

**Comment by pillarsdotnet** [comment]
Requires a [version update](https://travis-ci.org/simp/pupmod-simp-simp/jobs/553897914).

**Pull request closed without merging**
