### PR TITLE
(SIMP-6921) Allow puppetlabs/concat 6.x.

### PR DESCRIPTION
**Pull request by pillarsdotnet**

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@pillarsdotnet Can you rebase this please?

**Comment by pillarsdotnet** [comment]
Re-opened.

**Comment by pillarsdotnet** [comment]
Failures appear unrelated to patch.  Closing/reopening to re-kick tests.

**Comment by pillarsdotnet** [comment]
I don't understand the following test failures:
- https://travis-ci.org/simp/pupmod-simp-simp/jobs/567928491
```
867fatal: unable to access 'https://github.com/simp/pupmod-simp-ssh/': Failed to connect to github.com port 443: Connection timed out
868fatal: unable to access 'https://github.com/simp/pupmod-simp-sudosh/': Failed to connect to github.com port 443: Connection timed out
869fatal: unable to access 'https://github.com/simp/pupmod-simp-stunnel/': Failed to connect to github.com port 443: Connection timed out
870fatal: unable to access 'https://github.com/simp/pupmod-simp-simp_options/': Failed to connect to github.com port 443: Connection timed out
871fatal: unable to access 'https://github.com/simp/pupmod-simp-sudo/': Failed to connect to github.com port 443: Connection timed out
872fatal: unable to access 'https://github.com/simp/puppetlabs-stdlib/': Failed to connect to github.com port 443: Connection timed out
873fatal: unable to access 'https://github.com/simp/pupmod-simp-sssd/': Failed to connect to github.com port 443: Connection timed out
874rake aborted!
875Failed to clone git repository https://github.com/simp/pupmod-simp-sudosh into spec/fixtures/modules/sudosh
```
- https://travis-ci.org/simp/pupmod-simp-simp/jobs/567928497
```
864fatal: unable to access 'https://github.com/simp/puppetlabs-stdlib/': Failed to connect to github.com port 443: Connection timed out
865fatal: unable to access 'https://github.com/simp/pupmod-simp-stunnel/': Failed to connect to github.com port 443: Connection timed out
866fatal: unable to access 'https://github.com/simp/pupmod-simp-sssd/': Failed to connect to github.com port 443: Connection timed out
867rake aborted!
868fatal: unable to access 'https://github.com/simp/pupmod-simp-simp_options/': Failed to connect to github.com port 443: Connection timed out
869Failed to clone git repository https://github.com/simp/pupmod-simp-stunnel into spec/fixtures/modules/stunnel
870/home/travis/build/simp/pupmod-simp-simp/.vendor/ruby/2.4.0/gems/puppetlabs_spec_helper-2.14.1/lib/puppetlabs_spec_helper/tasks/fixtures.rb:150:in `clone_repo'
```

**Comment by pillarsdotnet** [comment]
Looks like tests are passing now.

**Pull request merged**
